In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Data Encoding

As we all know that better encoding leads to a better model and most algorithms cannot handle the categorical variables unless they are converted into a numerical value.
1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding 

1. **Nominal/One Hot Encoding**

**One Hot Encoding** is a method for converting categorical variables into a binary format. It creates new binary columns (0s and 1s) for each category in the original variable. Each category in the original column is represented as a separate column, where a value of 1 indicates the presence of that category, and 0 indicates its absence.

One hot encoding ,also known for as nominal encoding ,is a technique used to represent categorical data as numerical data,which is more suitable for the machine learning algorithm. In this techniques ,each category is represented as binary vector where each bit correspond to a unique category .for examole ,if we have categorical variable "color" with three possible values(red,green,blue),we can represent it using one hot encoding like:
1. Red:[1,0,0]
2. Green:[0,1,0]
3. Blue:[0,0,1]

In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder


In [2]:
#creating a simple dataframe 
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [4]:
#create an instance of onehotencoder
encoder = OneHotEncoder()

In [8]:
#perform fit() and Transform
result= encoder.fit_transform(df[['color']])
print(type(result))
print(result.toarray())

<class 'scipy.sparse._csr.csr_matrix'>
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [12]:
import pandas as pd
encoder_df = pd.DataFrame(result.toarray(),columns = encoder.get_feature_names_out())
encoder_df

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [13]:
pd.concat([df,encoder_df],axis = 1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0