In [24]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures .

In [25]:
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 25.0
[notice] To update, run: pip install --upgrade pip


In [26]:
import numpy as np

#create arrays using numpy
#creating 1D array
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [27]:
arr2 = np.array([1,2,3,4])
print(arr2.reshape((1,4)))#1 row and 4 col
print(arr2.shape)

[[1 2 3 4]]
(4,)


In [28]:
arr2 =np.array([[1,2,3,4,5]])
print(arr2.shape)
print(arr2)

(1, 5)
[[1 2 3 4 5]]


In [29]:
#2D arrays
arr3 =np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(arr3.shape)
print(arr3)

(2, 5)
[[1 2 3 4 5]
 [3 4 5 6 7]]


In [30]:
#creating the array using inbuilt function 
arr4= np.arange(0,10,2)
print(arr4)
print(arr4.size)

#reshapiing the single dimension array into the 2d array 
arr5= np.arange(0,10,2).reshape(5,1)
print(arr5)
print(arr5.shape)

#ones  and zeros inbuilt function 
arr6 = np.ones((3,4))
print(arr6)
print(arr6.shape)
arr7 = np.zeros((3,5))
print(arr7)
print(arr7.shape)

[0 2 4 6 8]
5
[[0]
 [2]
 [4]
 [6]
 [8]]
(5, 1)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)


In [31]:
#create an identity metrix 
arr_iden = np.eye(3)
print(arr_iden)
print(arr_iden.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [32]:
#attributes of numpy
arr = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
(3, 4)
2
12
int64
8


In [33]:
#vectorized numpy operation 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition
print("Addition:",arr1+arr2)

#element wise substraction 
print("substraction",arr1-arr2)

#element wise multiplication 
print("mul:",arr1*arr2)

#element wise division
print("div:",arr1/arr2)

print("etc")

Addition: [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
mul: [ 10  40  90 160 250]
div: [0.1 0.1 0.1 0.1 0.1]
etc


In [34]:
#Mathematical  function 
arr = np.array([2,3,4,5,6])

#square root
print("square root:",np.sqrt(arr))

#exponential 
print("exponential:",np.exp(arr))

#sine
print("sin fintion:",np.sin(arr))

#natural log 
print("natural log function:",np.log(arr))


square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
sin fintion: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
natural log function: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [35]:
#array slicing and indexing 
arr = np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13]])
print("Array:\n",arr)

print(arr[0][2])
print(arr[1:,2:])
print(arr[0:3,3:])
print(arr[0:2,2:])
print(arr[1:,1:3])

Array:
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]
3
[[ 7  8  9]
 [11 12 13]]
[[ 4  5]
 [ 8  9]
 [12 13]]
[[3 4 5]
 [7 8 9]]
[[ 6  7]
 [10 11]]


In [36]:
#modification of the array element
arr[0,0] =100
print(arr)
arr[1:] =101
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]
 [  9  10  11  12  13]]
[[100   2   3   4   5]
 [101 101 101 101 101]
 [101 101 101 101 101]]


In [37]:
#Statistical concept-Normalization
#to have a mean of 0(zero) and standard_deviation of 1(one)

data = np.array([100,101,200,121,23,122,2,1])

#calculating the mean and statndard deviation 
mean = np.mean(data)
std_dev =np.std(data)

#normalization of the data
normalized_data = (data-mean)/std_dev
print("Normalized data:",normalized_data)



Normalized data: [ 0.24872469  0.26403083  1.77933818  0.57015353 -0.9298477   0.58545966
 -1.25127653 -1.26658266]


In [38]:
data= np.array([1,2,3,4,5,6,7,8,9,10])

#maen
mean = np.mean(data)
print("mean:\n",mean)

#Median
median =np.median(data)
print("Median:\n",median)

#Standard deviation
std_dev =np.std(data)
print("Standard_deviation:\n",std_dev)

#variance
var = np.var(data)
print("Variance:\n",var)




mean:
 5.5
Median:
 5.5
Standard_deviation:
 2.8722813232690143
Variance:
 8.25


In [42]:
##Logical operation 
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
#print(data[(data>5) & (data<5)])


[False False False False False  True  True  True  True  True]
